# Generated by Django 5.0.1 on 2024-02-12 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=55)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='upload-image-dev', upload_to='gunasoApp/images/developers')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('x', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('tagone', models.CharField(max_length=10)),
                ('tagtwo', models.CharField(max_length=10)),
                ('slug', models.CharField(default='slugthis', max_length=130)),
                ('image', models.ImageField(blank=True, default='upload-image', upload_to='gunasoApp/images/topicimages')),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfessGroup',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Groupname', models.CharField(max_length=30)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(blank=True, max_length=130, unique=True)),
                ('image', models.ImageField(blank=True, default='upload-image', upload_to='gunasoApp/images/groupImages')),
                ('introduction', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clipping',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipping_user', to=settings.AUTH_USER_MODEL)),
                ('visitedUser', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='clipping_user_visited', to=settings.AUTH_USER_MODEL)),
                ('visitedGroup', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='clipping_group_visited', to='gunasoApp.confessgroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsComments',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gunasoApp.groupscomments')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gunasoApp.confessgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndexProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='upload-image', upload_to='gunasoApp/images/indexpost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='IndexProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, default='upload-image-feature', upload_to='gunasoApp/images/featureImgs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='upload-image', upload_to='gunasoApp/images/loggeduserImages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('storySubject', models.CharField(blank=True, max_length=255)),
                ('storyType', models.CharField(blank=True, max_length=50)),
                ('storyContent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gunasoApp.topiccomment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gunasoApp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('visitedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
