# Generated by Django 5.0.1 on 2024-02-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gunasoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confessgroup',
            name='tagline',
        ),
    ]
