# Generated by Django 5.0.1 on 2024-02-12 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunasoApp', '0002_remove_clipping_visitedgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupclipping',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipping_user_forgroup', to=settings.AUTH_USER_MODEL)),
                ('visitedGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipping_group_visited', to='gunasoApp.confessgroup')),
            ],
        ),
    ]
