# Generated by Django 4.1.7 on 2023-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunasoApp', '0002_topiccomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='upload-image-dev', upload_to='gunasoApp/images/developers')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('x', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
            ],
        ),
    ]
