# Generated by Django 5.0.1 on 2024-02-13 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunasoApp', '0003_groupclipping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyclipping',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipping_user_forstory', to=settings.AUTH_USER_MODEL)),
                ('visitedStory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipping_story_visited', to='gunasoApp.story')),
            ],
        ),
    ]
