# Generated by Django 5.0.1 on 2024-02-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunasoApp', '0003_groupscomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupscomments',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gunasoApp.confessgroup'),
        ),
    ]
