# Generated by Django 4.1.7 on 2023-12-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunasoApp', '0003_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=55)),
                ('content', models.TextField()),
            ],
        ),
    ]
